In [47]:
pip install xgboost


   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 1.3 MB/s eta 0:01:38
   ---------------------------------------- 0.5/124.9 MB 7.0 MB/s eta 0:00:18
   ---------------------------------------- 1.3/124.9 MB 13.4 MB/s eta 0:00:10
    --------------------------------------- 2.1/124.9 MB 16.5 MB/s eta 0:00:08
    --------------------------------------- 2.9/124.9 MB 16.6 MB/s eta 0:00:08
   - -------------------------------------- 3.6/124.9 MB 17.9 MB/s eta 0:00:07
   - -------------------------------------- 4.5/124.9 MB 18.9 MB/s eta 0:00:07
   - -------------------------------------- 5.2/124.9 MB 18.6 MB/s eta 0:00:07
   - -------------------------------------- 6.0/124.9 MB 19.2 MB/s eta 0:00:07
   -- ------------------------------------- 6.8/124.9 MB 19.8 MB/s eta 0:00:06
   -- ------------------------------------- 7.6/124.9 MB 20.2 MB/s eta 0:00:06
   -- ------------------------------------- 8.4/124.9 MB 19.8 

In [31]:
pip install imbalanced-learn


   ---------------------------------------- 0.0/258.3 kB ? eta -:--:--
   ------ -------------------------------- 41.0/258.3 kB 960.0 kB/s eta 0:00:01
   ---------------------------------------- 258.3/258.3 kB 3.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import os

import os

# Define the directory path
directory_path = r"C:\Users\kamru\Documents\Homograph"

# Initialize lists to store directories and file paths
directories = []
file_paths = []

#Walk through the directory and get directories and files

for root, dirs, files in os.walk(directory_path):
    #Add directories to the list
    for dir_name in dirs:
        directories.append(os.path.join(root, dir_name))

    #Add file paths to the list
    for file_name in files:
        file_paths.append(os.path.join(root, file_name))

#Print all directories
print("Directories")
for dir_path in directories:
    print(dir_path)

#Print all file path
print("\nFile Paths")
for file_path in file_paths:
    print(file_path)
    

Directories
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged
C:\Users\kamru\Documents\Homograph\bangla_tts_wsd
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\bol_bolo
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\dak_dako
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\kal_kalo
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\komol_komlo
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\mot_moto
C:\Users\kamru\Documents\Homograph\bangla_tts_wsd\scripts

File Paths
C:\Users\kamru\Documents\Homograph\bangla_homograph.zip
C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged.rar
C:\Users\kamru\Documents\Homograph\cc.bn.300.vec.gz
C:\Users\kamru\Documents\Homograph\clean_corpus.txt
C:\Users\kamru\Documents\Homograph\homograph_word.docx
C:\Users\kamru\Documents\Homograph\homograph_word.txt
C:\Users\kamru\Documents\Homograph\M1_presentation.ppt
C:\Users\kamru\Documents\Homograph\main.ipynb
C:\Users\kamru\Documents\Homograp

In [3]:
pip install scikit-learn


  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.0 MB 2.0 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/11.0 MB 11.6 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/11.0 MB 13.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.3/11.0 MB 16.2 MB/s eta 0:00:01
   ----------- ---------------------------- 3.1/11.0 MB 17.7 MB/s eta 0:00:01
   ------------- -------------------------- 3.8/11.0 MB 18.9 MB/s eta 0:00:01
   ---------------- ----------------------- 4.6/11.0 MB 18.4 MB/s eta 0:00:01
   ------------------- -------------------- 5.4/11.0 MB 19.2 MB/s eta 0:00:01
   ---------------------- ----------------- 6.2/11.0 MB 19.9 MB/s eta 0:00:01
   ------------------------- -------------- 7.0/11.0 MB 20.4 MB/s eta 0:00:01
   ----------------

In [11]:
# Import necessary libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Function to read and preprocess text files
def read_and_preprocess(file_path, label):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    # Remove extra spaces and add a label
    data = [(line.strip(), label) for line in lines if line.strip()]
    return data

# Function to combine multiple labeled datasets into a single DataFrame
def combine_data(*data_sets):
    combined_data = []
    for data in data_sets:
        combined_data.extend(data)
    return pd.DataFrame(combined_data, columns=['text', 'label'])

# Function to vectorize text data using TF-IDF
def vectorize_text(data_frame):
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X = vectorizer.fit_transform(data_frame['text'])
    return X, data_frame['label'], vectorizer

# Function to train a Naive Bayes model
def train_naive_bayes(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    model = MultinomialNB()
    model.fit(X_train, y_train)
    return model, X_test, y_test

# Function to evaluate the model
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report


In [14]:
# Use double backslashes for file paths
dak_data = read_and_preprocess("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dak.txt", 'dak')
dako_data = read_and_preprocess("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dako.txt", 'dako')


In [15]:
# Combine the dak and dako data into a single DataFrame
df = combine_data(dak_data, dako_data)


In [16]:
# Vectorize the text data using TF-IDF
X, y, vectorizer = vectorize_text(df)


In [17]:
# Train a Naive Bayes model on the vectorized data
model, X_test, y_test = train_naive_bayes(X, y)


In [18]:
# Evaluate the model and print the results
accuracy, conf_matrix, class_report = evaluate_model(model, X_test, y_test)

# Print the evaluation results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Model Accuracy: 0.8212121212121212
Confusion Matrix:
 [[259   0]
 [ 59  12]]
Classification Report:
               precision    recall  f1-score   support

         dak       0.81      1.00      0.90       259
        dako       1.00      0.17      0.29        71

    accuracy                           0.82       330
   macro avg       0.91      0.58      0.59       330
weighted avg       0.85      0.82      0.77       330



Full Code Block for bol_bolo:


In [20]:
# Reading and Preprocessing Bol and Bolo Data
bol_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\bol_bolo\Bol.txt"
bolo_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\bol_bolo\Bolo.txt"

bol_data = read_and_preprocess(bol_path, 'bol')
bolo_data = read_and_preprocess(bolo_path, 'bolo')

# Combine Bol and Bolo Data
df_bol_bolo = combine_data(bol_data, bolo_data)

# Vectorize the Text Data
X_bol_bolo, y_bol_bolo, vectorizer_bol_bolo = vectorize_text(df_bol_bolo)

# Train the Naive Bayes Model
model_bol_bolo, X_test_bol_bolo, y_test_bol_bolo = train_naive_bayes(X_bol_bolo, y_bol_bolo)

# Evaluate the Model
accuracy_bol_bolo, conf_matrix_bol_bolo, class_report_bol_bolo = evaluate_model(model_bol_bolo, X_test_bol_bolo, y_test_bol_bolo)

# Print Results
print("Bol_Bolo Model Accuracy:", accuracy_bol_bolo)
print("Bol_Bolo Confusion Matrix:\n", conf_matrix_bol_bolo)
print("Bol_Bolo Classification Report:\n", class_report_bol_bolo)


Bol_Bolo Model Accuracy: 0.9112021857923497
Bol_Bolo Confusion Matrix:
 [[657   0]
 [ 65  10]]
Bol_Bolo Classification Report:
               precision    recall  f1-score   support

         bol       0.91      1.00      0.95       657
        bolo       1.00      0.13      0.24        75

    accuracy                           0.91       732
   macro avg       0.95      0.57      0.59       732
weighted avg       0.92      0.91      0.88       732



In [24]:
# Import necessary libraries and define functions (if not already imported/defined)

# Reading and Preprocessing Kal and Kalo Data
kal_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\kal_kalo\Kal.txt"
kalo_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\kal_kalo\kalo.txt"

kal_data = read_and_preprocess(kal_path, 'kal')
kalo_data = read_and_preprocess(kalo_path, 'kalo')

# Combine Kal and Kalo Data
df_kal_kalo = combine_data(kal_data, kalo_data)

# Vectorize the Text Data
X_kal_kalo, y_kal_kalo, vectorizer_kal_kalo = vectorize_text(df_kal_kalo)

# Train the Naive Bayes Model
model_kal_kalo, X_test_kal_kalo, y_test_kal_kalo = train_naive_bayes(X_kal_kalo, y_kal_kalo)

# Evaluate the Model
accuracy_kal_kalo, conf_matrix_kal_kalo, class_report_kal_kalo = evaluate_model(model_kal_kalo, X_test_kal_kalo, y_test_kal_kalo)

# Print Results
print("Kal_Kalo Model Accuracy:", accuracy_kal_kalo)
print("Kal_Kalo Confusion Matrix:\n", conf_matrix_kal_kalo)
print("Kal_Kalo Classification Report:\n", class_report_kal_kalo)


Kal_Kalo Model Accuracy: 0.9312080536912751
Kal_Kalo Confusion Matrix:
 [[1105    0]
 [  82    5]]
Kal_Kalo Classification Report:
               precision    recall  f1-score   support

         kal       0.93      1.00      0.96      1105
        kalo       1.00      0.06      0.11        87

    accuracy                           0.93      1192
   macro avg       0.97      0.53      0.54      1192
weighted avg       0.94      0.93      0.90      1192



In [27]:
# Import necessary libraries and define functions (if not already imported/defined)

# Reading and Preprocessing Komol and Komlo Data
komol_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\komol_komlo\komol.txt"
komlo_path = r"C:\Users\kamru\Documents\Homograph\bangla_homograph_tagged\komol_komlo\komlo.txt"

komol_data = read_and_preprocess(komol_path, 'komol')
komlo_data = read_and_preprocess(komlo_path, 'komlo')

# Combine Komol and Komlo Data
df_komol_komlo = combine_data(komol_data, komlo_data)

# Vectorize the Text Data
X_komol_komlo, y_komol_komlo, vectorizer_komol_komlo = vectorize_text(df_komol_komlo)

# Train the Naive Bayes Model
model_komol_komlo, X_test_komol_komlo, y_test_komol_komlo = train_naive_bayes(X_komol_komlo, y_komol_komlo)

# Evaluate the Model
accuracy_komol_komlo, conf_matrix_komol_komlo, class_report_komol_komlo = evaluate_model(model_komol_komlo, X_test_komol_komlo, y_test_komol_komlo)

# Print Results
print("Komol_Komlo Model Accuracy:", accuracy_komol_komlo)
print("Komol_Komlo Confusion Matrix:\n", conf_matrix_komol_komlo)
print("Komol_Komlo Classification Report:\n", class_report_komol_komlo)


Komol_Komlo Model Accuracy: 0.8828828828828829
Komol_Komlo Confusion Matrix:
 [[73  0]
 [13 25]]
Komol_Komlo Classification Report:
               precision    recall  f1-score   support

       komlo       0.85      1.00      0.92        73
       komol       1.00      0.66      0.79        38

    accuracy                           0.88       111
   macro avg       0.92      0.83      0.86       111
weighted avg       0.90      0.88      0.88       111



In [33]:
from imblearn.under_sampling import RandomUnderSampler

# Define the evaluate_model_zero_division function (if not defined already)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def evaluate_model_zero_division(model, X_test, y_test):
    """Evaluates the model and returns accuracy, confusion matrix, and classification report."""
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)  # Use zero_division to handle undefined metrics
    return accuracy, conf_matrix, class_report

# Re-run the code after defining the function
accuracy_mot_moto_resampled, conf_matrix_mot_moto_resampled, class_report_mot_moto_resampled = evaluate_model_zero_division(model_mot_moto_resampled, X_test_mot_moto_resampled, y_test_mot_moto_resampled)

# Print results for the resampled model
print("Mot_Moto Resampled Model Accuracy:", accuracy_mot_moto_resampled)
print("Mot_Moto Resampled Confusion Matrix:\n", conf_matrix_mot_moto_resampled)
print("Mot_Moto Resampled Classification Report:\n", class_report_mot_moto_resampled)


Mot_Moto Resampled Model Accuracy: 0.71875
Mot_Moto Resampled Confusion Matrix:
 [[11  5]
 [ 4 12]]
Mot_Moto Resampled Classification Report:
               precision    recall  f1-score   support

         mot       0.73      0.69      0.71        16
        moto       0.71      0.75      0.73        16

    accuracy                           0.72        32
   macro avg       0.72      0.72      0.72        32
weighted avg       0.72      0.72      0.72        32



In [35]:
# Reading and Preprocessing Dak and Dako Data
dak_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dak.txt", 'dak')
dako_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dako.txt", 'dako')

# Combine Dak and Dako Data
df_dak_dako = combine_data(dak_data, dako_data)

# Vectorize the Text Data for Dak_Dako
X_dak_dako, y_dak_dako, vectorizer_dak_dako = vectorize_text(df_dak_dako)




# Reading and Preprocessing Bol and Bolo Data
bol_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bol.txt", 'bol')
bolo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bolo.txt", 'bolo')

# Combine Bol and Bolo Data
df_bol_bolo = combine_data(bol_data, bolo_data)

# Vectorize the Text Data for Bol_Bolo
X_bol_bolo, y_bol_bolo, vectorizer_bol_bolo = vectorize_text(df_bol_bolo)





# Reading and Preprocessing Kal and Kalo Data
kal_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\Kal.txt", 'kal')
kalo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\kalo.txt", 'kalo')

# Combine Kal and Kalo Data
df_kal_kalo = combine_data(kal_data, kalo_data)

# Vectorize the Text Data for Kal_Kalo
X_kal_kalo, y_kal_kalo, vectorizer_kal_kalo = vectorize_text(df_kal_kalo)




# Reading and Preprocessing Komol and Komlo Data
komol_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komol.txt", 'komol')
komlo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komlo.txt", 'komlo')

# Combine Komol and Komlo Data
df_komol_komlo = combine_data(komol_data, komlo_data)

# Vectorize the Text Data for Komol_Komlo
X_komol_komlo, y_komol_komlo, vectorizer_komol_komlo = vectorize_text(df_komol_komlo)




# Reading and Preprocessing Mot and Moto Data
mot_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\mot.txt", 'mot')
moto_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\moto.txt", 'moto')

# Combine Mot and Moto Data
df_mot_moto = combine_data(mot_data, moto_data)

# Vectorize the Text Data for Mot_Moto
X_mot_moto, y_mot_moto, vectorizer_mot_moto = vectorize_text(df_mot_moto)





In [37]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

# Train and evaluate an SVM model
def train_evaluate_svm(X, y, homograph_name):
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    
    # Train SVM model
    model_svm = SVC(kernel='linear', random_state=42, class_weight='balanced')
    model_svm.fit(X_train, y_train)
    
    # Evaluate the model
    y_pred = model_svm.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    
    # Print the evaluation results
    print(f"{homograph_name} SVM Model Accuracy: {accuracy}")
    print(f"{homograph_name} SVM Confusion Matrix:\n", conf_matrix)
    print(f"{homograph_name} SVM Classification Report:\n", class_report)
    
    # Return model and test data for further evaluation if needed
    return model_svm, X_test, y_test



In [38]:
# Function to read and preprocess text files
def read_and_preprocess(file_path, label):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    data = [(line.strip(), label) for line in lines if line.strip()]
    return data

# Function to combine multiple labeled datasets into a single DataFrame
def combine_data(*data_sets):
    combined_data = []
    for data in data_sets:
        combined_data.extend(data)
    return pd.DataFrame(combined_data, columns=['text', 'label'])

# Function to vectorize text data using TF-IDF
def vectorize_text(data_frame):
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X = vectorizer.fit_transform(data_frame['text'])
    return X, data_frame['label'], vectorizer


In [39]:
# Dak_Dako
dak_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dak.txt", 'dak')
dako_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dako.txt", 'dako')
df_dak_dako = combine_data(dak_data, dako_data)
X_dak_dako, y_dak_dako, vectorizer_dak_dako = vectorize_text(df_dak_dako)

# Bol_Bolo
bol_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bol.txt", 'bol')
bolo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bolo.txt", 'bolo')
df_bol_bolo = combine_data(bol_data, bolo_data)
X_bol_bolo, y_bol_bolo, vectorizer_bol_bolo = vectorize_text(df_bol_bolo)

# Kal_Kalo
kal_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\Kal.txt", 'kal')
kalo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\kalo.txt", 'kalo')
df_kal_kalo = combine_data(kal_data, kalo_data)
X_kal_kalo, y_kal_kalo, vectorizer_kal_kalo = vectorize_text(df_kal_kalo)

# Komol_Komlo
komol_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komol.txt", 'komol')
komlo_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komlo.txt", 'komlo')
df_komol_komlo = combine_data(komol_data, komlo_data)
X_komol_komlo, y_komol_komlo, vectorizer_komol_komlo = vectorize_text(df_komol_komlo)

# Mot_Moto
mot_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\mot.txt", 'mot')
moto_data = read_and_preprocess(r"C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\moto.txt", 'moto')
df_mot_moto = combine_data(mot_data, moto_data)
X_mot_moto, y_mot_moto, vectorizer_mot_moto = vectorize_text(df_mot_moto)


In [40]:
# Train and evaluate SVM for Dak_Dako
model_svm_dak_dako, X_test_dak_dako, y_test_dak_dako = train_evaluate_svm(X_dak_dako, y_dak_dako, 'Dak_Dako')

# Train and evaluate SVM for Bol_Bolo
model_svm_bol_bolo, X_test_bol_bolo, y_test_bol_bolo = train_evaluate_svm(X_bol_bolo, y_bol_bolo, 'Bol_Bolo')

# Train and evaluate SVM for Kal_Kalo
model_svm_kal_kalo, X_test_kal_kalo, y_test_kal_kalo = train_evaluate_svm(X_kal_kalo, y_kal_kalo, 'Kal_Kalo')

# Train and evaluate SVM for Komol_Komlo
model_svm_komol_komlo, X_test_komol_komlo, y_test_komol_komlo = train_evaluate_svm(X_komol_komlo, y_komol_komlo, 'Komol_Komlo')

# Train and evaluate SVM for Mot_Moto
model_svm_mot_moto, X_test_mot_moto, y_test_mot_moto = train_evaluate_svm(X_mot_moto, y_mot_moto, 'Mot_Moto')


Dak_Dako SVM Model Accuracy: 0.9333333333333333
Dak_Dako SVM Confusion Matrix:
 [[246  13]
 [  9  62]]
Dak_Dako SVM Classification Report:
               precision    recall  f1-score   support

         dak       0.96      0.95      0.96       259
        dako       0.83      0.87      0.85        71

    accuracy                           0.93       330
   macro avg       0.90      0.91      0.90       330
weighted avg       0.94      0.93      0.93       330

Bol_Bolo SVM Model Accuracy: 0.9453551912568307
Bol_Bolo SVM Confusion Matrix:
 [[636  21]
 [ 19  56]]
Bol_Bolo SVM Classification Report:
               precision    recall  f1-score   support

         bol       0.97      0.97      0.97       657
        bolo       0.73      0.75      0.74        75

    accuracy                           0.95       732
   macro avg       0.85      0.86      0.85       732
weighted avg       0.95      0.95      0.95       732

Kal_Kalo SVM Model Accuracy: 0.9429530201342282
Kal_Kalo SVM Confu

In [41]:
from sklearn.linear_model import LogisticRegression

# Train and evaluate a Logistic Regression model
def train_evaluate_logistic_regression(X, y, homograph_name):
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    
    # Train Logistic Regression model
    model_lr = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
    model_lr.fit(X_train, y_train)
    
    # Evaluate the model
    y_pred = model_lr.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    
    # Print the evaluation results
    print(f"{homograph_name} Logistic Regression Model Accuracy: {accuracy}")
    print(f"{homograph_name} Logistic Regression Confusion Matrix:\n", conf_matrix)
    print(f"{homograph_name} Logistic Regression Classification Report:\n", class_report)
    
    # Return model and test data for further evaluation if needed
    return model_lr, X_test, y_test


In [42]:
# Train and evaluate Logistic Regression for Dak_Dako
model_lr_dak_dako, X_test_dak_dako, y_test_dak_dako = train_evaluate_logistic_regression(X_dak_dako, y_dak_dako, 'Dak_Dako')

# Train and evaluate Logistic Regression for Bol_Bolo
model_lr_bol_bolo, X_test_bol_bolo, y_test_bol_bolo = train_evaluate_logistic_regression(X_bol_bolo, y_bol_bolo, 'Bol_Bolo')

# Train and evaluate Logistic Regression for Kal_Kalo
model_lr_kal_kalo, X_test_kal_kalo, y_test_kal_kalo = train_evaluate_logistic_regression(X_kal_kalo, y_kal_kalo, 'Kal_Kalo')

# Train and evaluate Logistic Regression for Komol_Komlo
model_lr_komol_komlo, X_test_komol_komlo, y_test_komol_komlo = train_evaluate_logistic_regression(X_komol_komlo, y_komol_komlo, 'Komol_Komlo')

# Train and evaluate Logistic Regression for Mot_Moto
model_lr_mot_moto, X_test_mot_moto, y_test_mot_moto = train_evaluate_logistic_regression(X_mot_moto, y_mot_moto, 'Mot_Moto')


Dak_Dako Logistic Regression Model Accuracy: 0.9212121212121213
Dak_Dako Logistic Regression Confusion Matrix:
 [[244  15]
 [ 11  60]]
Dak_Dako Logistic Regression Classification Report:
               precision    recall  f1-score   support

         dak       0.96      0.94      0.95       259
        dako       0.80      0.85      0.82        71

    accuracy                           0.92       330
   macro avg       0.88      0.89      0.89       330
weighted avg       0.92      0.92      0.92       330

Bol_Bolo Logistic Regression Model Accuracy: 0.9508196721311475
Bol_Bolo Logistic Regression Confusion Matrix:
 [[637  20]
 [ 16  59]]
Bol_Bolo Logistic Regression Classification Report:
               precision    recall  f1-score   support

         bol       0.98      0.97      0.97       657
        bolo       0.75      0.79      0.77        75

    accuracy                           0.95       732
   macro avg       0.86      0.88      0.87       732
weighted avg       0.95  

In [44]:
from sklearn.ensemble import RandomForestClassifier

# Train and evaluate a Random Forest model
def train_evaluate_random_forest(X, y, homograph_name):
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    
    # Train Random Forest model
    model_rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    model_rf.fit(X_train, y_train)
    
    # Evaluate the model
    y_pred = model_rf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    
    # Print the evaluation results
    print(f"{homograph_name} Random Forest Model Accuracy: {accuracy}")
    print(f"{homograph_name} Random Forest Confusion Matrix:\n", conf_matrix)
    print(f"{homograph_name} Random Forest Classification Report:\n", class_report)
    
    # Return model and test data for further evaluation if needed
    return model_rf, X_test, y_test


In [45]:
# Train and evaluate Random Forest for Dak_Dako
model_rf_dak_dako, X_test_dak_dako, y_test_dak_dako = train_evaluate_random_forest(X_dak_dako, y_dak_dako, 'Dak_Dako')

# Train and evaluate Random Forest for Bol_Bolo
model_rf_bol_bolo, X_test_bol_bolo, y_test_bol_bolo = train_evaluate_random_forest(X_bol_bolo, y_bol_bolo, 'Bol_Bolo')

# Train and evaluate Random Forest for Kal_Kalo
model_rf_kal_kalo, X_test_kal_kalo, y_test_kal_kalo = train_evaluate_random_forest(X_kal_kalo, y_kal_kalo, 'Kal_Kalo')

# Train and evaluate Random Forest for Komol_Komlo
model_rf_komol_komlo, X_test_komol_komlo, y_test_komol_komlo = train_evaluate_random_forest(X_komol_komlo, y_komol_komlo, 'Komol_Komlo')

# Train and evaluate Random Forest for Mot_Moto
model_rf_mot_moto, X_test_mot_moto, y_test_mot_moto = train_evaluate_random_forest(X_mot_moto, y_mot_moto, 'Mot_Moto')


Dak_Dako Random Forest Model Accuracy: 0.9333333333333333
Dak_Dako Random Forest Confusion Matrix:
 [[240  19]
 [  3  68]]
Dak_Dako Random Forest Classification Report:
               precision    recall  f1-score   support

         dak       0.99      0.93      0.96       259
        dako       0.78      0.96      0.86        71

    accuracy                           0.93       330
   macro avg       0.88      0.94      0.91       330
weighted avg       0.94      0.93      0.94       330

Bol_Bolo Random Forest Model Accuracy: 0.9685792349726776
Bol_Bolo Random Forest Confusion Matrix:
 [[648   9]
 [ 14  61]]
Bol_Bolo Random Forest Classification Report:
               precision    recall  f1-score   support

         bol       0.98      0.99      0.98       657
        bolo       0.87      0.81      0.84        75

    accuracy                           0.97       732
   macro avg       0.93      0.90      0.91       732
weighted avg       0.97      0.97      0.97       732

Kal_Ka

In [55]:
# Train and evaluate an XGBoost model without the 'use_label_encoder' parameter
def train_evaluate_xgboost(X, y, homograph_name):
    # Label encode the target variable
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded)
    
    # Train XGBoost model
    model_xgb = XGBClassifier(eval_metric='mlogloss', random_state=42)  # Removed 'use_label_encoder'
    model_xgb.fit(X_train, y_train)
    
    # Evaluate the model
    y_pred = model_xgb.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    
    # Print the evaluation results
    print(f"{homograph_name} XGBoost Model Accuracy: {accuracy}")
    print(f"{homograph_name} XGBoost Confusion Matrix:\n", conf_matrix)
    print(f"{homograph_name} XGBoost Classification Report:\n", class_report)
    
    # Return model and test data for further evaluation if needed
    return model_xgb, X_test, y_test


In [56]:
# Train and evaluate XGBoost for Dak_Dako
model_xgb_dak_dako, X_test_dak_dako, y_test_dak_dako = train_evaluate_xgboost(X_dak_dako, y_dak_dako, 'Dak_Dako')

# Train and evaluate XGBoost for Bol_Bolo
model_xgb_bol_bolo, X_test_bol_bolo, y_test_bol_bolo = train_evaluate_xgboost(X_bol_bolo, y_bol_bolo, 'Bol_Bolo')

# Train and evaluate XGBoost for Kal_Kalo
model_xgb_kal_kalo, X_test_kal_kalo, y_test_kal_kalo = train_evaluate_xgboost(X_kal_kalo, y_kal_kalo, 'Kal_Kalo')

# Train and evaluate XGBoost for Komol_Komlo
model_xgb_komol_komlo, X_test_komol_komlo, y_test_komol_komlo = train_evaluate_xgboost(X_komol_komlo, y_komol_komlo, 'Komol_Komlo')

# Train and evaluate XGBoost for Mot_Moto
model_xgb_mot_moto, X_test_mot_moto, y_test_mot_moto = train_evaluate_xgboost(X_mot_moto, y_mot_moto, 'Mot_Moto')


Dak_Dako XGBoost Model Accuracy: 0.9393939393939394
Dak_Dako XGBoost Confusion Matrix:
 [[248  11]
 [  9  62]]
Dak_Dako XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96       259
           1       0.85      0.87      0.86        71

    accuracy                           0.94       330
   macro avg       0.91      0.92      0.91       330
weighted avg       0.94      0.94      0.94       330

Bol_Bolo XGBoost Model Accuracy: 0.9549180327868853
Bol_Bolo XGBoost Confusion Matrix:
 [[649   8]
 [ 25  50]]
Bol_Bolo XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.99      0.98       657
           1       0.86      0.67      0.75        75

    accuracy                           0.95       732
   macro avg       0.91      0.83      0.86       732
weighted avg       0.95      0.95      0.95       732

Kal_Kalo XGBoost Model Accuracy: 0.9521812

In [59]:
# Import necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Function for Hyperparameter Tuning of SVM
def hyperparameter_tuning_svm(X, y):
    param_grid = {
        'C': [0.1, 1, 10, 100],
        'gamma': [1, 0.1, 0.01, 0.001],
        'kernel': ['linear', 'rbf']
    }
    grid_search = GridSearchCV(SVC(class_weight='balanced', random_state=42), param_grid, cv=3, scoring='accuracy')
    grid_search.fit(X, y)
    print(f"Best Hyperparameters for SVM: {grid_search.best_params_}")
    print(f"Best SVM Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_

# Function for Hyperparameter Tuning of Logistic Regression
def hyperparameter_tuning_logistic_regression(X, y):
    param_grid = {
        'C': [0.01, 0.1, 1, 10, 100],
        'solver': ['newton-cg', 'lbfgs', 'liblinear']
    }
    grid_search = GridSearchCV(LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000), param_grid, cv=3, scoring='accuracy')
    grid_search.fit(X, y)
    print(f"Best Hyperparameters for Logistic Regression: {grid_search.best_params_}")
    print(f"Best Logistic Regression Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_

# Function for Hyperparameter Tuning of Random Forest
def hyperparameter_tuning_random_forest(X, y):
    param_grid = {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 10, 20, 30],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
    }
    grid_search = GridSearchCV(RandomForestClassifier(class_weight='balanced', random_state=42), param_grid, cv=3, scoring='accuracy')
    grid_search.fit(X, y)
    print(f"Best Hyperparameters for Random Forest: {grid_search.best_params_}")
    print(f"Best Random Forest Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_

# Function for Hyperparameter Tuning of XGBoost
def hyperparameter_tuning_xgboost(X, y):
    param_grid = {
        'n_estimators': [50, 100, 150],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1, 0.2],
        'subsample': [0.8, 1.0],
        'colsample_bytree': [0.8, 1.0]
    }
    grid_search = GridSearchCV(XGBClassifier(eval_metric='mlogloss', random_state=42), param_grid, cv=3, scoring='accuracy')
    grid_search.fit(X, y)
    print(f"Best Hyperparameters for XGBoost: {grid_search.best_params_}")
    print(f"Best XGBoost Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_


In [61]:
from sklearn.preprocessing import LabelEncoder

# Function for Hyperparameter Tuning of XGBoost with Label Encoding
def hyperparameter_tuning_xgboost(X, y):
    # Encode labels as integers
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    # Define hyperparameter grid
    param_grid = {
        'n_estimators': [50, 100, 150],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1, 0.2],
        'subsample': [0.8, 1.0],
        'colsample_bytree': [0.8, 1.0]
    }
    grid_search = GridSearchCV(XGBClassifier(eval_metric='mlogloss', random_state=42), param_grid, cv=3, scoring='accuracy')
    grid_search.fit(X, y_encoded)
    
    print(f"Best Hyperparameters for XGBoost: {grid_search.best_params_}")
    print(f"Best XGBoost Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_


In [62]:
# Assuming you have preprocessed and vectorized data for all homographs:
# Dak_Dako: X_dak_dako, y_dak_dako
# Bol_Bolo: X_bol_bolo, y_bol_bolo
# Kal_Kalo: X_kal_kalo, y_kal_kalo
# Komol_Komlo: X_komol_komlo, y_komol_komlo
# Mot_Moto: X_mot_moto, y_mot_moto

# Hyperparameter Tuning for Dak_Dako
print("Hyperparameter Tuning for Dak_Dako")
best_svm_dak_dako = hyperparameter_tuning_svm(X_dak_dako, y_dak_dako)
best_lr_dak_dako = hyperparameter_tuning_logistic_regression(X_dak_dako, y_dak_dako)
best_rf_dak_dako = hyperparameter_tuning_random_forest(X_dak_dako, y_dak_dako)
best_xgb_dak_dako = hyperparameter_tuning_xgboost(X_dak_dako, y_dak_dako)  # Updated function with Label Encoding

# Hyperparameter Tuning for Bol_Bolo
print("\nHyperparameter Tuning for Bol_Bolo")
best_svm_bol_bolo = hyperparameter_tuning_svm(X_bol_bolo, y_bol_bolo)
best_lr_bol_bolo = hyperparameter_tuning_logistic_regression(X_bol_bolo, y_bol_bolo)
best_rf_bol_bolo = hyperparameter_tuning_random_forest(X_bol_bolo, y_bol_bolo)
best_xgb_bol_bolo = hyperparameter_tuning_xgboost(X_bol_bolo, y_bol_bolo)  # Updated function with Label Encoding

# Hyperparameter Tuning for Kal_Kalo
print("\nHyperparameter Tuning for Kal_Kalo")
best_svm_kal_kalo = hyperparameter_tuning_svm(X_kal_kalo, y_kal_kalo)
best_lr_kal_kalo = hyperparameter_tuning_logistic_regression(X_kal_kalo, y_kal_kalo)
best_rf_kal_kalo = hyperparameter_tuning_random_forest(X_kal_kalo, y_kal_kalo)
best_xgb_kal_kalo = hyperparameter_tuning_xgboost(X_kal_kalo, y_kal_kalo)  # Updated function with Label Encoding

# Hyperparameter Tuning for Komol_Komlo
print("\nHyperparameter Tuning for Komol_Komlo")
best_svm_komol_komlo = hyperparameter_tuning_svm(X_komol_komlo, y_komol_komlo)
best_lr_komol_komlo = hyperparameter_tuning_logistic_regression(X_komol_komlo, y_komol_komlo)
best_rf_komol_komlo = hyperparameter_tuning_random_forest(X_komol_komlo, y_komol_komlo)
best_xgb_komol_komlo = hyperparameter_tuning_xgboost(X_komol_komlo, y_komol_komlo)  # Updated function with Label Encoding

# Hyperparameter Tuning for Mot_Moto
print("\nHyperparameter Tuning for Mot_Moto")
best_svm_mot_moto = hyperparameter_tuning_svm(X_mot_moto, y_mot_moto)
best_lr_mot_moto = hyperparameter_tuning_logistic_regression(X_mot_moto, y_mot_moto)
best_rf_mot_moto = hyperparameter_tuning_random_forest(X_mot_moto, y_mot_moto)
best_xgb_mot_moto = hyperparameter_tuning_xgboost(X_mot_moto, y_mot_moto)  # Updated function with Label Encoding


Hyperparameter Tuning for Dak_Dako
Best Hyperparameters for SVM: {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
Best SVM Model Accuracy: 0.9434862888938792
Best Hyperparameters for Logistic Regression: {'C': 10, 'solver': 'newton-cg'}
Best Logistic Regression Model Accuracy: 0.9033385732465006
Best Hyperparameters for Random Forest: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
Best Random Forest Model Accuracy: 0.9133792449534646
Best Hyperparameters for XGBoost: {'colsample_bytree': 1.0, 'learning_rate': 0.2, 'max_depth': 5, 'n_estimators': 150, 'subsample': 0.8}
Best XGBoost Model Accuracy: 0.9170421937769793

Hyperparameter Tuning for Bol_Bolo
Best Hyperparameters for SVM: {'C': 100, 'gamma': 1, 'kernel': 'linear'}
Best SVM Model Accuracy: 0.951209512095121
Best Hyperparameters for Logistic Regression: {'C': 100, 'solver': 'newton-cg'}
Best Logistic Regression Model Accuracy: 0.9553095530955309
Best Hyperparameters for Random Forest: {'max_depth'

In [65]:
# Import necessary libraries for hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

# Function for Hyperparameter Tuning of Naive Bayes
def hyperparameter_tuning_naive_bayes(X, y):
    # Define hyperparameter grid for Naive Bayes
    param_grid = {
        'alpha': [0.01, 0.1, 0.5, 1, 2, 5, 10]  # Smoothing parameter
    }
    # Create GridSearchCV with MultinomialNB
    grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=3, scoring='accuracy')
    # Fit the grid search to the data
    grid_search.fit(X, y)
    
    # Print the best hyperparameters and the best score
    print(f"Best Hyperparameters for Naive Bayes: {grid_search.best_params_}")
    print(f"Best Naive Bayes Model Accuracy: {grid_search.best_score_}")
    return grid_search.best_estimator_

# Hyperparameter Tuning for Dak_Dako
print("Hyperparameter Tuning for Naive Bayes - Dak_Dako")
best_naive_bayes_dak_dako = hyperparameter_tuning_naive_bayes(X_dak_dako, y_dak_dako)

# Hyperparameter Tuning for Bol_Bolo
print("\nHyperparameter Tuning for Naive Bayes - Bol_Bolo")
best_naive_bayes_bol_bolo = hyperparameter_tuning_naive_bayes(X_bol_bolo, y_bol_bolo)

# Hyperparameter Tuning for Kal_Kalo
print("\nHyperparameter Tuning for Naive Bayes - Kal_Kalo")
best_naive_bayes_kal_kalo = hyperparameter_tuning_naive_bayes(X_kal_kalo, y_kal_kalo)

# Hyperparameter Tuning for Komol_Komlo
print("\nHyperparameter Tuning for Naive Bayes - Komol_Komlo")
best_naive_bayes_komol_komlo = hyperparameter_tuning_naive_bayes(X_komol_komlo, y_komol_komlo)

# Hyperparameter Tuning for Mot_Moto
print("\nHyperparameter Tuning for Naive Bayes - Mot_Moto")
best_naive_bayes_mot_moto = hyperparameter_tuning_naive_bayes(X_mot_moto, y_mot_moto)



Hyperparameter Tuning for Naive Bayes - Dak_Dako
Best Hyperparameters for Naive Bayes: {'alpha': 0.01}
Best Naive Bayes Model Accuracy: 0.8623474810988846

Hyperparameter Tuning for Naive Bayes - Bol_Bolo
Best Hyperparameters for Naive Bayes: {'alpha': 0.01}
Best Naive Bayes Model Accuracy: 0.9430094300943009

Hyperparameter Tuning for Naive Bayes - Kal_Kalo
Best Hyperparameters for Naive Bayes: {'alpha': 0.01}
Best Naive Bayes Model Accuracy: 0.951409869083585

Hyperparameter Tuning for Naive Bayes - Komol_Komlo
Best Hyperparameters for Naive Bayes: {'alpha': 0.5}
Best Naive Bayes Model Accuracy: 0.9190707229652942

Hyperparameter Tuning for Naive Bayes - Mot_Moto
Best Hyperparameters for Naive Bayes: {'alpha': 0.5}
Best Naive Bayes Model Accuracy: 0.9609730606184922


In [73]:
# Suppress specific warnings
import warnings
warnings.filterwarnings(action='ignore', category=UserWarning, module='xgboost')

# Import necessary libraries
from xgboost import XGBClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

# Function to read and preprocess text files
def read_and_preprocess(file_path, label):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    # Remove extra spaces and add a label
    data = [(line.strip(), label) for line in lines if line.strip()]
    return data

# Function to combine multiple labeled datasets into a single DataFrame
def combine_data(*data_sets):
    combined_data = []
    for data in data_sets:
        combined_data.extend(data)
    return pd.DataFrame(combined_data, columns=['text', 'label'])

# Function to vectorize text data using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

def vectorize_text(data_frame):
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 3))  # Using n-grams up to 3
    X = vectorizer.fit_transform(data_frame['text'])
    return X, data_frame['label'], vectorizer

# Function to evaluate the model with zero_division handling
def evaluate_model_zero_division(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    return accuracy, conf_matrix, class_report

# Function to train and evaluate models
def train_evaluate_model(X, y, model, model_name, homograph_name):
    # Encode the labels before training
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)
    
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded)
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Evaluate the model
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, zero_division=0)
    
    print(f"--- {homograph_name} {model_name} Performance ---")
    print(f"Accuracy: {accuracy}")
    print(f"Confusion Matrix:\n{conf_matrix}")
    print(f"Classification Report:\n{class_report}\n")

# File paths for each homograph pair
file_paths_dak_dako = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dak.txt", 'dak'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dako.txt", 'dako')
]
file_paths_bol_bolo = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bol.txt", 'bol'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\bol_bolo\\Bolo.txt", 'bolo')
]
file_paths_kal_kalo = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\Kal.txt", 'kal'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\kal_kalo\\kalo.txt", 'kalo')
]
file_paths_komol_komlo = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komol.txt", 'komol'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\komol_komlo\\komlo.txt", 'komlo')
]
file_paths_mot_moto = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\mot.txt", 'mot'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\mot_moto\\moto.txt", 'moto')
]

# Function to process and evaluate each homograph dataset with multiple models
def process_and_evaluate_homograph(homograph_name, file_paths):
    # Read and preprocess data for each file
    data = []
    for file_path, label in file_paths:
        data.extend(read_and_preprocess(file_path, label))
    
    # Combine and vectorize the text data
    df_homograph = combine_data(data)
    X_homograph, y_homograph, vectorizer_homograph = vectorize_text(df_homograph)
    
    # Define models to evaluate
    models = {
        'Naive Bayes': MultinomialNB(),
        'SVM': SVC(probability=True),
        'Logistic Regression': LogisticRegression(max_iter=2000),
        'Random Forest': RandomForestClassifier(random_state=42),
        'XGBoost': XGBClassifier(eval_metric='mlogloss', random_state=42, use_label_encoder=False)
    }
    
    # Train and evaluate each model
    for model_name, model in models.items():
        train_evaluate_model(X_homograph, y_homograph, model, model_name, homograph_name)

# Process and evaluate each homograph dataset
process_and_evaluate_homograph("Dak_Dako", file_paths_dak_dako)
process_and_evaluate_homograph("Bol_Bolo", file_paths_bol_bolo)
process_and_evaluate_homograph("Kal_Kalo", file_paths_kal_kalo)
process_and_evaluate_homograph("Komol_Komlo", file_paths_komol_komlo)
process_and_evaluate_homograph("Mot_Moto", file_paths_mot_moto)


--- Dak_Dako Naive Bayes Performance ---
Accuracy: 0.8212121212121212
Confusion Matrix:
[[259   0]
 [ 59  12]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      1.00      0.90       259
           1       1.00      0.17      0.29        71

    accuracy                           0.82       330
   macro avg       0.91      0.58      0.59       330
weighted avg       0.85      0.82      0.77       330


--- Dak_Dako SVM Performance ---
Accuracy: 0.9212121212121213
Confusion Matrix:
[[257   2]
 [ 24  47]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.99      0.95       259
           1       0.96      0.66      0.78        71

    accuracy                           0.92       330
   macro avg       0.94      0.83      0.87       330
weighted avg       0.92      0.92      0.92       330


--- Dak_Dako Logistic Regression Performance ---
Accuracy: 0.8515151515151516
Confus

In [74]:
pip install transformers torch


     ---------------------------------------- 0.0/43.7 kB ? eta -:--:--
     -------------------------- ----------- 30.7/43.7 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 43.7/43.7 kB 711.0 kB/s eta 0:00:00
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     ---------------------------------------- 41.5/41.5 kB 2.1 MB/s eta 0:00:00
  Using cached tokenizers-0.19.1-cp310-none-win_amd64.whl.metadata (6.9 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.6/9.5 MB 19.8 MB/s eta 0:00:01
   ------ --------------------------------- 1.4/9.5 MB 18.2 MB/s eta 0:00:01
   --------- ------------------------------ 2.2/9.5 MB 20.0 MB/s eta 0:00:01
   ------------ --------------------------- 3.0/9.5 MB 21.2 MB/s eta 0:00:01
   ---------------- ----------------------- 3.8/9.5 MB 22.0 MB/s eta 0:00:01
   ------------------- 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbconvert 7.16.3 requires beautifulsoup4, which is not installed.
nbconvert 7.16.3 requires bleach!=5.0.0, which is not installed.
nbconvert 7.16.3 requires defusedxml, which is not installed.
nbconvert 7.16.3 requires jupyterlab-pygments, which is not installed.
nbconvert 7.16.3 requires nbclient>=0.5.0, which is not installed.
nbconvert 7.16.3 requires nbformat>=5.7, which is not installed.
nbconvert 7.16.3 requires pandocfilters>=1.4.1, which is not installed.
nbconvert 7.16.3 requires tinycss2, which is not installed.


In [75]:
# Import necessary libraries
import pandas as pd
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Ensure reproducibility
torch.manual_seed(42)

# Custom Dataset class for BERT
class HomographDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.texts)
    
    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

# Load BERT Tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Function to encode labels to numerical values
def encode_labels(labels):
    label_map = {label: idx for idx, label in enumerate(set(labels))}
    return [label_map[label] for label in labels], label_map

# Load and preprocess your dataset
def prepare_data(file_paths, tokenizer, max_length):
    data = []
    labels = []
    for file_path, label_name in file_paths:
        with open(file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            data.extend([line.strip() for line in lines if line.strip()])
            labels.extend([label_name] * len(lines))
    encoded_labels, label_map = encode_labels(labels)
    return data, encoded_labels, label_map

# Prepare the data for Dak_Dako (as an example, extend this to other homographs)
file_paths_dak_dako = [
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dak.txt", 'dak'),
    ("C:\\Users\\kamru\\Documents\\Homograph\\bangla_homograph_tagged\\dak_dako\\dako.txt", 'dako')
]

# Preprocess data
texts, labels, label_map = prepare_data(file_paths_dak_dako, tokenizer, max_length=128)

# Train-test split
X_train, X_val, y_train, y_val = train_test_split(texts, labels, test_size=0.2, random_state=42, stratify=labels)

# Create Dataset objects
train_dataset = HomographDataset(X_train, y_train, tokenizer, max_length=128)
val_dataset = HomographDataset(X_val, y_val, tokenizer, max_length=128)

# Load pre-trained BERT model for sequence classification
model = BertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=len(label_map))

# Training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    evaluation_strategy="epoch",
    save_strategy="epoch"
)

# Define a custom function for computing metrics
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# Train the model
trainer.train()

# Evaluate the model
trainer.evaluate()


c:\Users\kamru\.conda\envs\py310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (c:\Users\kamru\.conda\envs\py310\lib\site-packages\google\protobuf\internal\__init__.py)

In [79]:
pip uninstall transformers torch

^C
